/* ==========================================================
   NÉU — Product Catalog
   Prices in ZAR (R). Each size carries its own priceDelta
   which is added to the base price.
   ========================================================== */

const CLOTHING_SIZES = [
  { label: 'XS', priceDelta: 0 },
  { label: 'S', priceDelta: 0 },
  { label: 'M', priceDelta: 0 },
  { label: 'L', priceDelta: 0 },
  { label: 'XL', priceDelta: 60 },
  { label: 'XXL', priceDelta: 120 },
];

const SHOE_SIZES = [
  { label: 'UK 5', priceDelta: 0 },
  { label: 'UK 6', priceDelta: 0 },
  { label: 'UK 7', priceDelta: 0 },
  { label: 'UK 8', priceDelta: 0 },
  { label: 'UK 9', priceDelta: 40 },
  { label: 'UK 10', priceDelta: 40 },
  { label: 'UK 11', priceDelta: 80 },
];

const BELT_SIZES = [
  { label: '30"', priceDelta: 0 },
  { label: '32"', priceDelta: 0 },
  { label: '34"', priceDelta: 30 },
  { label: '36"', priceDelta: 30 },
  { label: '38"', priceDelta: 60 },
];

const WATCH_SIZES = [
  { label: '36mm', priceDelta: 0 },
  { label: '40mm', priceDelta: 150 },
  { label: '44mm', priceDelta: 300 },
];

const ONE_SIZE = [{ label: 'One Size', priceDelta: 0 }];

const PRODUCTS = [
  /* ============ ACCESSORIES ============ */
  {
    id: 'acc-regatta-watch',
    category: 'Accessories',
    subcategory: 'Watches',
    name: 'Regatta Two-Tone Watch',
    price: 2450,
    description: 'A clean, minimal dial finished in gold-tone steel on a striped navy and forest nylon strap. Water-resistant to 30m, with a scratch-resistant mineral crystal face — built for every day, sharp enough for the office.',
    details: ['Gold-tone stainless steel case', 'Navy & forest striped NATO strap', 'Water-resistant 30m', 'Japanese quartz movement', '2-year warranty'],
    images: ['assets/products/accessory_1.jpg'],
    sizes: WATCH_SIZES,
    tag: 'New',
    unisex: true,
  },
  {
    id: 'acc-layered-necklace',
    category: 'Accessories',
    subcategory: 'Jewellery',
    name: 'Layered Chain Necklace Set',
    price: 890,
    description: 'Three fine chains layered to different lengths, finished with a delicate initial charm and a single emerald-cut stone drop. Tarnish-resistant plating for daily wear.',
    details: ['18k gold-plated brass', 'Tarnish resistant', 'Adjustable clasp, 3 lengths', 'Comes in a Néu jewellery pouch'],
    images: ['assets/products/accessory_2.jpg'],
    sizes: ONE_SIZE,
    tag: null,
    unisex: true,
  },
  {
    id: 'acc-heritage-belt',
    category: 'Accessories',
    subcategory: 'Belts',
    name: 'Heritage Leather Belt',
    price: 780,
    salePrice: 590,
    description: 'Full-grain leather belt with a solid brushed-nickel buckle. Hand-cut and burnished at the edges for a lived-in finish that only improves with age.',
    details: ['Full-grain leather', 'Brushed nickel buckle', 'Stitched edge detail', 'Available in tan and black'],
    images: ['assets/products/accessory_3.jpg'],
    sizes: BELT_SIZES,
    tag: null,
    unisex: true,
  },
  {
    id: 'acc-aria-watch',
    category: 'Accessories',
    subcategory: 'Watches',
    name: 'Aria Mesh Strap Watch',
    price: 2150,
    description: 'A softer silhouette with a fine mesh strap and a warm rose-tone case. The slim profile slips easily under a cuff without losing presence.',
    details: ['Rose-tone stainless steel', 'Fine mesh strap, adjustable', 'Water-resistant 30m', 'Sapphire-coated crystal'],
    images: ['assets/products/accessory_4.jpg'],
    sizes: WATCH_SIZES,
    tag: 'New',
    unisex: false,
  },
  {
    id: 'acc-ambassador-watch',
    category: 'Accessories',
    subcategory: 'Watches',
    name: 'Ambassador Leather Strap Watch',
    price: 2690,
    description: 'A formal dress watch with a silver case and jet-black leather strap. Understated enough for a boardroom, sharp enough for a black-tie evening.',
    details: ['Polished stainless steel case', 'Genuine leather strap', 'Water-resistant 30m', 'Interchangeable strap pins'],
    images: ['assets/products/accessory_5.jpg'],
    sizes: WATCH_SIZES,
    tag: null,
    unisex: false,
  },

  /* ============ JACKETS ============ */
  {
    id: 'jkt-rosso-trench',
    category: 'Jackets',
    subcategory: 'Coats',
    name: 'Rosso Leather Trench',
    price: 4890,
    description: 'A double-breasted leather trench with a full self-tie belt and clean, structured lapels. Cut long for a dramatic silhouette that layers effortlessly over tailoring or denim.',
    details: ['Genuine leather shell', 'Full self-tie belt', 'Double-breasted button closure', 'Interior pockets', 'Dry clean only'],
    images: ['assets/products/Jackets_1.jpg'],
    sizes: CLOTHING_SIZES,
    tag: 'Limited',
    unisex: false,
  },
  {
    id: 'jkt-noir-leather',
    category: 'Jackets',
    subcategory: 'Leather Jackets',
    name: 'Noir Leather Jacket',
    price: 3450,
    description: 'A tailored leather jacket with notch lapels and a cropped, blazer-inspired cut. Soft-touch lambskin with a satin interior lining for a jacket that moves with you.',
    details: ['Lambskin leather', 'Notch lapel, blazer cut', 'Satin interior lining', 'Two front welt pockets'],
    images: ['assets/products/Jackets_2.jpg'],
    sizes: CLOTHING_SIZES,
    tag: null,
    unisex: false,
  },
  {
    id: 'jkt-ledger-blazer',
    category: 'Jackets',
    subcategory: 'Blazers',
    name: 'Ledger Pinstripe Blazer',
    price: 2980,
    description: 'A relaxed, oversized blazer in a fine navy pinstripe wool blend. Structured shoulders soften into a fluid drape — equally at home over a tee or tailoring.',
    details: ['Wool blend, navy pinstripe', 'Oversized, relaxed fit', 'Fully lined', 'Single button closure'],
    images: ['assets/products/Jackets_3.jpg'],
    sizes: CLOTHING_SIZES,
    tag: 'New',
    unisex: true,
  },
  {
    id: 'jkt-glacier-puffer',
    category: 'Jackets',
    subcategory: 'Outerwear',
    name: 'Glacier Puffer Jacket',
    price: 3190,
    description: 'An oversized long-line puffer in matte white technical shell, filled for genuine cold-weather performance. Detachable hood and a zip-through storm flap for the harshest mornings.',
    details: ['Water-resistant technical shell', 'Insulated fill', 'Detachable hood', 'Unisex, true to size'],
    images: ['assets/products/Jackets_4.jpg', 'assets/products/Trouser_2.jpg'],
    sizes: CLOTHING_SIZES,
    tag: 'Bestseller',
    unisex: true,
  },
  {
    id: 'jkt-scarlet-bomber',
    category: 'Jackets',
    subcategory: 'Bombers',
    name: 'Scarlet Leather Bomber',
    price: 3690,
    salePrice: 2950,
    description: 'A statement leather bomber in deep scarlet with ribbed collar, cuffs and hem. Finished with subtle tonal stitching for a jacket built to be noticed.',
    details: ['Genuine leather', 'Ribbed knit collar & cuffs', 'Zip-through front', 'Regular fit'],
    images: ['assets/products/jacket_bomber.jpg'],
    sizes: CLOTHING_SIZES,
    tag: null,
    unisex: false,
  },
  {
    id: 'jkt-trackside-varsity',
    category: 'Jackets',
    subcategory: 'Varsity',
    name: 'Trackside Varsity Jacket',
    price: 2890,
    description: 'A motorsport-inspired varsity jacket loaded with embroidered patches and bold graphic panelling. A conversation-starter built on premium satin and wool-blend sleeves.',
    details: ['Wool-blend body, satin sleeves', 'Embroidered patch detailing', 'Snap-button front', 'Ribbed collar, cuffs & hem'],
    images: ['assets/products/jacket_varsity.jpg'],
    sizes: CLOTHING_SIZES,
    tag: 'New',
    unisex: true,
  },

  /* ============ T-SHIRTS ============ */
  {
    id: 'tee-essential-crew',
    category: 'T-Shirts',
    subcategory: 'Crewneck',
    name: 'Essential Crewneck Tee',
    price: 420,
    description: 'The foundation tee — heavyweight 220gsm combed cotton with a clean crewneck and a boxy, considered fit. Pre-shrunk and garment-dyed for a soft hand-feel from the first wash.',
    details: ['220gsm combed cotton', 'Garment-dyed', 'Boxy regular fit', 'Available in Black, White, Navy'],
    images: ['assets/products/T_sshirt_1.jpg'],
    sizes: CLOTHING_SIZES,
    tag: 'Bestseller',
    unisex: true,
  },
  {
    id: 'tee-classic-unisex',
    category: 'T-Shirts',
    subcategory: 'Crewneck',
    name: 'Classic Unisex Tee',
    price: 380,
    salePrice: 290,
    description: 'A true unisex staple cut with a straight hem and dropped shoulder seam so it sits well on every frame. Soft-washed cotton jersey that only gets better with age.',
    details: ['100% cotton jersey', 'Dropped shoulder seam', 'Straight hem', 'Unisex sizing'],
    images: ['assets/products/T_sshirt_2.jpg'],
    sizes: CLOTHING_SIZES,
    tag: null,
    unisex: true,
  },
  {
    id: 'tee-oversized-drop',
    category: 'T-Shirts',
    subcategory: 'Oversized',
    name: 'Oversized Drop-Shoulder Tee',
    price: 460,
    description: 'An oversized silhouette with an extended drop shoulder and a longer body length for that off-duty, effortless look. Heavyweight cotton that holds its shape wear after wear.',
    details: ['260gsm heavyweight cotton', 'Extended drop shoulder', 'Longer body length', 'Ribbed crewneck collar'],
    images: ['assets/products/T_sshirt_4.jpg'],
    sizes: CLOTHING_SIZES,
    tag: 'New',
    unisex: true,
  },
  {
    id: 'tee-relaxed-fit',
    category: 'T-Shirts',
    subcategory: 'Relaxed',
    name: 'Relaxed Fit Tee',
    price: 400,
    description: 'A relaxed, easy fit that sits just past the hip. Mid-weight jersey with a fine rib crewneck built to keep its shape through wash after wash.',
    details: ['180gsm cotton jersey', 'Relaxed fit', 'Fine rib crewneck', 'Available in Black, White, Navy'],
    images: ['assets/products/T_sshirt_5.jpg'],
    sizes: CLOTHING_SIZES,
    tag: null,
    unisex: true,
  },

  /* ============ TROUSERS ============ */
  {
    id: 'trs-wide-leg-tailored',
    category: 'Trousers',
    subcategory: 'Tailored',
    name: 'Wide-Leg Tailored Trouser',
    price: 1290,
    description: 'A sharply tailored wide-leg trouser in a soft grey wool blend, finished with a drawstring waist for a relaxed-meets-formal fit. Pleated front for a fuller, elegant drape.',
    details: ['Wool blend', 'Drawstring adjustable waist', 'Pleated front', 'Side pockets'],
    images: ['assets/products/Trouser_1.jpg'],
    sizes: CLOTHING_SIZES,
    tag: 'New',
    unisex: true,
  },
  {
    id: 'trs-cropped-cigarette',
    category: 'Trousers',
    subcategory: 'Cigarette',
    name: 'Cropped Cigarette Trouser',
    price: 1090,
    description: 'A slim, cropped cigarette trouser in warm ivory with a clean, unbroken front leg line. Designed to sit high on the waist and pair effortlessly with heels or flats.',
    details: ['Stretch tailoring fabric', 'Cropped ankle length', 'High-rise waist', 'Concealed side zip'],
    images: ['assets/products/Trouser_3.jpg'],
    sizes: CLOTHING_SIZES,
    tag: null,
    unisex: false,
  },
  {
    id: 'trs-camel-wide-leg',
    category: 'Trousers',
    subcategory: 'Wide Leg',
    name: 'Camel Wide-Leg Trouser',
    price: 1350,
    description: 'A high-waisted, floor-grazing wide-leg trouser in rich camel. Front pleats and a fluid drape make this the trouser that carries an entire outfit on its own.',
    details: ['Textured woven fabric', 'High-waisted fit', 'Front pleats', 'Side slit hem detail'],
    images: ['assets/products/Trouser_4.jpg'],
    sizes: CLOTHING_SIZES,
    tag: 'Bestseller',
    unisex: false,
  },
  {
    id: 'trs-relaxed-straight',
    category: 'Trousers',
    subcategory: 'Straight',
    name: 'Relaxed Straight Trouser',
    price: 1190,
    salePrice: 890,
    description: 'A relaxed straight-leg trouser in deep black pinstripe wool blend, cut for movement with a clean unbroken hem. Understated, versatile, built for every day.',
    details: ['Pinstripe wool blend', 'Relaxed straight leg', 'Belt loop waistband', 'Two side pockets, one back welt pocket'],
    images: ['assets/products/Trouser_5.jpg'],
    sizes: CLOTHING_SIZES,
    tag: null,
    unisex: true,
  },

  /* ============ SHOES ============ */
  {
    id: 'shoe-crystal-heel',
    category: 'Shoes',
    subcategory: 'Heels',
    name: 'Crystal Strap Heel',
    price: 1690,
    description: 'A refined pointed-toe heel in soft ivory satin with a crystal-embellished ankle strap. Balanced on a slim stiletto heel built for a full evening on your feet.',
    details: ['Satin upper', 'Crystal ankle strap detail', '90mm stiletto heel', 'Cushioned insole'],
    images: ['assets/products/shoes_1.jpg'],
    sizes: SHOE_SIZES,
    tag: 'New',
    unisex: false,
  },
  {
    id: 'shoe-court-sneaker',
    category: 'Shoes',
    subcategory: 'Sneakers',
    name: 'Court Leather Sneaker',
    price: 1450,
    salePrice: 1090,
    description: 'A minimal court sneaker in rich tan nubuck leather with a clean white cupsole. Understated branding and a contrast heel tab for a sneaker that pairs with everything.',
    details: ['Nubuck leather upper', 'White rubber cupsole', 'Contrast heel tab', 'Breathable textile lining'],
    images: ['assets/products/shoes_2.jpg'],
    sizes: SHOE_SIZES,
    tag: 'Bestseller',
    unisex: true,
  },
  {
    id: 'shoe-foundry-boot',
    category: 'Shoes',
    subcategory: 'Boots',
    name: 'Foundry Leather Boot',
    price: 2190,
    description: 'A rugged lace-up boot in burnished leather with a chunky lugged sole for genuine all-weather wear. Reinforced toe cap and speed-hook lacing for a fast, secure fit.',
    details: ['Full-grain burnished leather', 'Lugged rubber sole', 'Speed-hook lacing', 'Reinforced toe cap'],
    images: ['assets/products/shoes_3.jpg'],
    sizes: SHOE_SIZES,
    tag: null,
    unisex: true,
  },
  {
    id: 'shoe-chain-loafer',
    category: 'Shoes',
    subcategory: 'Loafers',
    name: 'Chain Trim Loafer',
    price: 1590,
    description: 'A chunky-soled patent loafer finished with a polished chain-link trim. The lugged platform sole brings a modern edge to an otherwise classic silhouette.',
    details: ['Patent leather upper', 'Chain-link hardware trim', 'Lugged platform sole', 'Cushioned footbed'],
    images: ['assets/products/shoes_4.jpg'],
    sizes: SHOE_SIZES,
    tag: 'New',
    unisex: false,
  },
  {
    id: 'shoe-pulse-runner',
    category: 'Shoes',
    subcategory: 'Sneakers',
    name: 'Pulse Runner Sneaker',
    price: 1790,
    description: 'A bold performance-inspired runner in fire-engine red with a chunky foam midsole. Breathable mesh panelling and a padded collar keep every mile comfortable.',
    details: ['Mesh & synthetic upper', 'Foam cushioned midsole', 'Padded ankle collar', 'Rubber outsole with traction pattern'],
    images: ['assets/products/shoes_5.jpg'],
    sizes: SHOE_SIZES,
    tag: 'Bestseller',
    unisex: true,
  },
];

const CATEGORIES = ['Accessories', 'Jackets', 'T-Shirts', 'Trousers', 'Shoes'];

const CATEGORY_BANNER = {
  'Accessories': 'assets/products/accessory_3.jpg',
  'Jackets': 'assets/products/Jackets_1.jpg',
  'T-Shirts': 'assets/products/T_sshirt_2.jpg',
  'Trousers': 'assets/products/Trouser_5.jpg',
  'Shoes': 'assets/products/shoes_3.jpg',
};

function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id);
}

function formatZAR(amount) {
  return 'R' + Number(amount).toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
